CC = cc
CFLAGS = -Wall -Wextra -Werror
SRC = main.c memory.c parsing.c number_to_words.c ft_strlen.c ft_atoi.c ft_strcat.c ft_strcpy.c ft_strdup.c
TARGET = rush-02

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)

fclean: clean
